package org.olcbox.app.crypt

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

@OptIn(ExperimentalEncodingApi::class)
class CryptCodecTest {
    // Fixtures generated by the Rust coordinator crypt_link::tests::print_fixture
    // (key = [42u8; 32]). This proves the Kotlin decoder is wire-compatible with
    // the server encoder.
    private val fixtureKeyB64 = "KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKio="
    private val fixtureBlob =
        "PUtUSvcFHP7RaUdnoe3kiTxMd5t8R2fhKbezwNn4b346MTOM9L_Efda6HedlY1EVxprVRQu-bTgBUwc38IT-23bvBIhBrlFmgOviGK__tX3d8jKEsvUkFKcdd3FnO39oQFSFVcZH6ATMTJuMH6O8Sw"
    private val expectedUrl = "https://proofkit.org/sub/TESTTOKEN/olcrtc?crypt=1"

    private fun codec(): CryptCodec =
        CryptCodec(CryptCodec.decodeMaster(fixtureKeyB64)!!)

    @Test
    fun decryptsRustFixtureBody() {
        assertEquals(expectedUrl, codec().decryptBody(fixtureBlob))
    }

    @Test
    fun decryptsWrappedLink() {
        val link = "olcrtc://crypt1/$fixtureBlob"
        assertEquals(expectedUrl, codec().decryptLink(link))
    }

    @Test
    fun plainLinkIsNotACryptLink() {
        assertNull(codec().decryptLink("olcrtc://telemost?vp8channel@room#key"))
    }

    @Test
    fun tamperedBlobRejected() {
        val bytes = Base64.UrlSafe.withPadding(Base64.PaddingOption.PRESENT_OPTIONAL).decode(fixtureBlob)
        bytes[bytes.size - 1] = (bytes[bytes.size - 1].toInt() xor 1).toByte()
        val tampered = Base64.UrlSafe.withPadding(Base64.PaddingOption.ABSENT).encode(bytes)
        assertNull(codec().decryptBody(tampered))
    }

    @Test
    fun decodeMasterRejectsBlankAndWrongLength() {
        // The "crypt disabled" path: no key / bad key ⇒ null (CryptCodec.default()
        // returns null on such input, so plain links still import).
        assertNull(CryptCodec.decodeMaster(""))
        assertNull(CryptCodec.decodeMaster("too-short"))
        assertEquals(32, CryptCodec.decodeMaster(fixtureKeyB64)!!.size)
    }

    @Test
    fun constantTimeEqualsWorks() {
        assertTrue(constantTimeEquals("abc", "abc"))
        assertTrue(!constantTimeEquals("abc", "abd"))
    }
}
